local categories = {
    editing = {
        hints = {
        {"r", "replace single character"},
        {"R", "enter replace mode"},
        {"J", "join line below"},
        {"gJ", "join line without space"},
        {"cc", "change entire line"},
        {"C", "change toend of line"},
        {"s", "substitute character"},
        {"S", "substitute line"},
        {"xp", "transpose letters"},
        {"u", "undo"},
        {"<C-r>", "redo"},
        {".", "repeat last command"},
        },
        header = "EDITING",
        color = "#ff6ac1",
        order = 0,
    },
    cut_paste = {
        hints = {
        {"yy", "yank line"},
        {"yw", "yank word"},
        {"y$", "yank to end of line"},
        {"p", "paste after"},
        {"P", "paste before"},
        {"dd", "delete line"},
        {"dw", "delete word"},
        {"D", "delete to end"},
        {"x", "delete char"},
        {"X", "delete before"},
        },
        header = "CUT_PASTE",
        color = "#ff9e64",
        order = 1,
    },
    insert = {
        hints = {
        {"i", "insert before"},
        {"I", "insert at line start"},
        {"a", "append after"},
        {"A", "append at end"},
        {"o", "open line below"},
        {"O", "open line above"},
        {"<Esc>", "exit insert"},
        },
        header = "INSERT",
        color = "#a6e22e",
        order = 2,
    },
    visual = {
        hints = {
            {"v", "visual mode"},
            {"V", "visual line"},
            {"<C-v>", "visual block"},
        },
        header = "VISUAL",
        color = "#c792ea",
        order = 3,
    },
    search = {
        hints = {
            {"/", "search forward"},
            {"?", "search backward"},
            {"n", "next match"},
            {"N", "prev match"},
            {"*", "search word forward"},
            {"#", "search word backward"},
        },
        header = "SEARCH",
        color = "#ffd866",
        order = 4,
    },
    movement = {
        hints = {
            {"h", "left"},
            {"j", "down"},
            {"k", "up"},
            {"l", "right"},
            {"w", "next word"},
            {"b", "prev word"},
            {"0", "line start"},
            {"$", "line end"},
            {"gg", "top"},
            {"G", "bottom"},
        },
        header = "MOVEMENT",
        color = "#6ac1ff",
        order = 5,
    }
}

return categories
